### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by lordcrekit** [lordcrekit/MI-449-SS17-740-css-frameworks-p1twXJ#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://lordcrekit.github.io/MI-449-SS17-740-css-frameworks-p1twXJ/) and meets the following criteria:

- [x] Include the CSS and JS for Bootstrap 3 (not 4) in the page (including the "jQuery" dependency)
- [x] Use the `container` class to center your page content
- [x] Use a `navbar` class to display the name of your site and a list of at least 3 links (to past projects, or anything else) at the top of your page
- [x] Split your main content into 2 columns on large (`lg`) and medium (`md`) sized screens, but collapse them on top of each other on small (`sm`) and extra small (`xs`) screens
- [x] Use a `thumbnail` class on an at least one image in your page

**Comment by KatieMFritz** [comment]
AHHHH YOU RICKROLLED ME! I love it. 😆 😆 😆 

You really went above and beyond on this project - readme, license, extra links, footer, jumbotron, favicon, SEO meta content, explanatory comments. I can see you're comfortable with Bootstrap. 👍 

### Including JQuery

```
<!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="public/js/bootstrap.min.js"></script>
```

Good thinking to include a backup to the CDN for JQuery! However, I don't see an actual copy of jquery.min.js in your project files. 😄 **Please either add one and update the file path in `index.html`, or get rid of that line and just use the CDN.** 

### Bootstrap Grid

Something weird is happening (at least on my machine) with your `.col-md-4` divs. They're collapsing to a single column when my viewport width is 1240px, which should only happen if they're `col-lg`, not `col-md`. I can't figure out why yet! I tried changing them to `.col-md-6` in Chrome Developer Tools, but I got the same behavior. **Did you change any of the breakpoints when you downloaded Bootstrap? Any ideas why this is happening?** If you have trouble recreating the behavior, we can do a video chat or work on it together during class tomorrow. 

In general, [it's also recommended](http://getbootstrap.com/examples/grid/) to use all 12 columns of the Bootstrap grid, even though it's not technically required. From a design perspective, it helps you make more efficient use of the available space, especially at larger breakpoints. There are cases where people don't do this, but in this class, we want you to master the rules before you start breaking them. **For purposes of Bootstrap mastery, could you please tweak your columns in the portfolio section so each row adds up to 12?** You can go to straight `.col-md-6` or play around with offsets, empty divs, etc. to get a different design. Up to you. If I were you, I'd do that first and see if that somehow fixes the md/large breakpoint issue above.

### Consistent Spacing and Indentation

There are two line breaks in `index.html` at the end before your javascript links, but you only use 1 line break in the rest of the file. **If this is on purpose, feel free to convince me why it should be that way. Otherwise, change it to just one line.** 

### Unique, descriptive commit messages

I won't give you my normal spiel about commit messages, because most of yours are great - unique, specific, descriptive. There's that one that just says `?` though. No need to change it, but try to avoid that in the future!

* * *

Again, great job on this project! Make those changes, [Slack me](https://lansingcodes.slack.com/messages/@katiemfritz/) or respond here if you have any questions, and comment when it's ready for another review. 😸

**Comment by lordcrekit** [comment]
All fixes included.

**Comment by KatieMFritz** [comment]
Nice work! 👍 Looks like I had my zoom level set to 125% on Chrome, which might have been messing with breakpoints. When I set zoom to 100%, it breaks at 992px, which seems more like it.

One tiny typo in that javascript backup link, that could cause a big headache if your CDN link failed:
`'<script src="./public/js/jquery-3.1.1".min.js><\/script>'`

The `"` should be after `min.js`, not before. Fix that, don't change anything else, and let me know. 😄

**Comment by lordcrekit** [comment]
Doh! I'll re-use the fixed version in future projects so I don't mess that up again.
Fixed.

**Comment by KatieMFritz** [comment]
There we go! [:shipit:](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
